# Generated by Django 4.1 on 2022-08-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.BooleanField(default=True, verbose_name='Статус (активный)')),
                ('image', models.ImageField(blank=True, max_length=250, null=True, upload_to='upload/images/food/', verbose_name='Изображение')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Приоритет')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('restaurant', models.CharField(max_length=250, verbose_name='id_организации')),
                ('category', models.CharField(blank=True, max_length=250, null=True, verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
