# Generated by Django 4.1 on 2022-08-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_label_integr', '0002_rename_food_bufferfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='СompoundSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_compaunds', models.CharField(choices=[('Iiko', 'Айко'), ('R_Keeper', 'Р-Kипер')], default='Iiko', max_length=8)),
                ('restaurant', models.CharField(max_length=250, verbose_name='id_организации')),
                ('user_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='Логин')),
                ('user_secret', models.CharField(blank=True, max_length=250, null=True, verbose_name='Пароль')),
                ('api_key', models.CharField(blank=True, max_length=500, null=True, verbose_name='API ключ')),
                ('url_token', models.URLField(blank=True, max_length=500, null=True, verbose_name='API ключ')),
            ],
        ),
    ]
